version: "1.0"
services:
  web:
    image: nginx:1.21.5
    container_name: pokemons-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: .
    container_name: pokemons-php
    volumes:
      - .:/var/www/html